// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.0
// source: id.proto

package gamepb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Protocol_Id int32

const (
	// request
	Protocol_PingReq         Protocol_Id = 0
	Protocol_CreateRoomReq   Protocol_Id = 2
	Protocol_ShutdownRoomReq Protocol_Id = 3
	Protocol_SaveRoomReq     Protocol_Id = 5
	// response
	Protocol_PingResp         Protocol_Id = 100
	Protocol_CreateRoomResp   Protocol_Id = 102
	Protocol_ShutdownRoomResp Protocol_Id = 103
	Protocol_SaveRoomResp     Protocol_Id = 105
)

// Enum value maps for Protocol_Id.
var (
	Protocol_Id_name = map[int32]string{
		0:   "PingReq",
		2:   "CreateRoomReq",
		3:   "ShutdownRoomReq",
		5:   "SaveRoomReq",
		100: "PingResp",
		102: "CreateRoomResp",
		103: "ShutdownRoomResp",
		105: "SaveRoomResp",
	}
	Protocol_Id_value = map[string]int32{
		"PingReq":          0,
		"CreateRoomReq":    2,
		"ShutdownRoomReq":  3,
		"SaveRoomReq":      5,
		"PingResp":         100,
		"CreateRoomResp":   102,
		"ShutdownRoomResp": 103,
		"SaveRoomResp":     105,
	}
)

func (x Protocol_Id) Enum() *Protocol_Id {
	p := new(Protocol_Id)
	*p = x
	return p
}

func (x Protocol_Id) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol_Id) Descriptor() protoreflect.EnumDescriptor {
	return file_id_proto_enumTypes[0].Descriptor()
}

func (Protocol_Id) Type() protoreflect.EnumType {
	return &file_id_proto_enumTypes[0]
}

func (x Protocol_Id) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol_Id.Descriptor instead.
func (Protocol_Id) EnumDescriptor() ([]byte, []int) {
	return file_id_proto_rawDescGZIP(), []int{0, 0}
}

type Protocol struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Protocol) Reset() {
	*x = Protocol{}
	if protoimpl.UnsafeEnabled {
		mi := &file_id_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Protocol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Protocol) ProtoMessage() {}

func (x *Protocol) ProtoReflect() protoreflect.Message {
	mi := &file_id_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Protocol.ProtoReflect.Descriptor instead.
func (*Protocol) Descriptor() ([]byte, []int) {
	return file_id_proto_rawDescGZIP(), []int{0}
}

var File_id_proto protoreflect.FileDescriptor

var file_id_proto_rawDesc = []byte{
	0x0a, 0x08, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73, 0x67, 0x22,
	0xa1, 0x01, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0x94, 0x01, 0x0a,
	0x02, 0x49, 0x64, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x10, 0x00,
	0x12, 0x11, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65,
	0x71, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x52,
	0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x61, 0x76, 0x65,
	0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x10, 0x05, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x10, 0x64, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x10, 0x66, 0x12, 0x14, 0x0a, 0x10, 0x53,
	0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x10,
	0x67, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x10, 0x69, 0x42, 0x11, 0x5a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x3b,
	0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_id_proto_rawDescOnce sync.Once
	file_id_proto_rawDescData = file_id_proto_rawDesc
)

func file_id_proto_rawDescGZIP() []byte {
	file_id_proto_rawDescOnce.Do(func() {
		file_id_proto_rawDescData = protoimpl.X.CompressGZIP(file_id_proto_rawDescData)
	})
	return file_id_proto_rawDescData
}

var file_id_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_id_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_id_proto_goTypes = []interface{}{
	(Protocol_Id)(0), // 0: msg.Protocol.Id
	(*Protocol)(nil), // 1: msg.Protocol
}
var file_id_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_id_proto_init() }
func file_id_proto_init() {
	if File_id_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_id_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Protocol); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_id_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_id_proto_goTypes,
		DependencyIndexes: file_id_proto_depIdxs,
		EnumInfos:         file_id_proto_enumTypes,
		MessageInfos:      file_id_proto_msgTypes,
	}.Build()
	File_id_proto = out.File
	file_id_proto_rawDesc = nil
	file_id_proto_goTypes = nil
	file_id_proto_depIdxs = nil
}
